name: oracledart
version: 0.0.14
author: Alexander Aprelev <alexander@aprelev.com>
homepage: https://github.com/aam/oracledart
description: Library to allow Dart server programs to talk to Oracle
dependencies:
  test: ">=0.11.0 <1.0.0"
