name: oracledart
version: 0.0.5
author: Alexander Aprelev <alexander@aprelev.com>
homepage: https://github.com/aam/oracledart
description: Library to allow Dart server programs to talk to Oracle
dependencies:
  unittest: ">=0.10.0 <0.11.0"
