name: oracledart
version: 0.0.1
author: Alexander Aprelev <alexander@aprelev.com>
homepage: https://github.com/aam/oracledart
description: Library to allow Dart server programs to talk to Oracle
dependencies:
  unittest: any
